version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: edu-mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rishi
      - MONGO_INITDB_ROOT_PASSWORD=rishi
  mongo-express:
    image: mongo-express
    container_name: edu-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rishi
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rishi
      - ME_CONFIG_MONGODB_SERVER=edu-mongodb
volumes:
  data: {}
networks:
  default:
    name: mongodb_network


